Update FAQ_uczestnicy.md
ls6/AgileWarsaw pull request #7
Opened 2018-01-05 15:49 UTC by jurkiewa

Niewielka zmiana wstępu i wprowadzenie punktacji, która moim zdaniem poprawia czytelność.

2018-01-05 16:39 UTC, ls6 commented on FAQ/FAQ_uczestnicy.md
> +Lista nie jest zamykana tuż przed rozpoczęciem spotkania---nie spełniałaby wtedy swojej głównej roli czyli polepszenia przewidywalności liczby obecnych. Wypisanie się ,,w ostatniej chwili'' może nada
To nie jest takie proste, ale trop jest dobry.

2018-01-05 16:45 UTC, ls6 commented on FAQ/FAQ_uczestnicy.md
> +Lista nie jest zamykana tuż przed rozpoczęciem spotkania---nie spełniałaby wtedy swojej głównej roli czyli polepszenia przewidywalności liczby obecnych. Wypisanie się ,,w ostatniej chwili'' może nada
Niestety nie da się tego uprościć do 48h—to wyprzedzenie zależy od paru czynników (weekend w środku, jaką mamy salę, elastyczność jej zmiany itp.)

2018-01-05 16:49 UTC, ls6 requested changes
Wielkie dzięki za te poprawki!

Ponieważ chciałbym, żeby było widać, że to Twoja kontrybucja a nie wiem jak (i czy można w ogóle) scalić tylko część poprawek wyklikam "request changes" zamiast zrobić to po prostu samemu bo te 48h nie zadziała.

Ale mogę też wprowadzić to samemu jeśli tak wolisz :)

2018-01-05 16:54 UTC, jurkiewa commented
Wszystko jedno, jak Ci wygodniej.

2018-01-05 16:54 UTC, jurkiewa commented
Ja i tak nie mogę akceptować requestu.

2018-01-06 12:28 UTC, merged

2018-01-06 12:29 UTC, ls6 commented
Dzięki Andrzej :)